### ISSUE TITLE
Add support for client-side TLS "Server Name Indication" (SNI)

### ISSUE THREAD

**Issue by rlebeau** [IndySockets/Indy#160]
http://en.wikipedia.org/wiki/Server_Name_Indication

Per http://stackoverflow.com/questions/5113333/:

> On the client side, you use SSL_set_tlsext_host_name(ssl, servername) before initiating the SSL connection.
>
> On the server side, it's a little more complicated:
> - Set up an additional SSL_CTX() for each different certificate;
> - Add a servername callback to each SSL_CTX() using SSL_CTX_set_tlsext_servername_callback();
> - In the callback, retrieve the client-supplied servername with SSL_get_servername(ssl, TLSEXT_NAMETYPE_host_name). Figure out the right SSL_CTX to go with that host name, then switch the SSL object to that SSL_CTX with SSL_set_SSL_CTX().
>
> The s_client.c and s_server.c files in the apps/ directory of the OpenSSL source distribution implement this functionality, so they're a good resource to see how it should be done.

**Comment by HeartWareDK** [comment]
Any progress to report on Server-Side SNI ?

**Comment by rlebeau** [comment]
Nothing that has been checked in yet. Some code changes were submitted to me awhile back ago, and I have incorporated them into my private dev copy of Indy, but I haven't had time to test and verify that things work before checking in to the public repository. I have no ETA on that at this time.
