### ISSUE TITLE
IdURI.pas cannot compile under Delphi 7

### ISSUE THREAD

**Issue by jakmoy** [IndySockets/Indy#178]
Version 4527: Updating TIdURI.PathEncode() and TIdURI.ParamsEncode() to not encode '%HH' sequences.

The new code uses "STRING_IS_UNICODE" directive. The alternative code for non-unicode environment misses "end" keywords.

Lines: 467, 552.
`for J := 0 to 2 do begin`

should be changed to
`for J := 0 to 2 do`

**Comment by rlebeau** [comment]
Fixed in SVN rev 5428
