### ISSUE TITLE
Wrong declarations in IdSSLOpenSSLHeaders.pas

### ISSUE THREAD

**Issue by LFriede** [IndySockets/Indy#188]
Hi, i found some mistakes in the mentioned header.

1.
```Delphi
EVP_get_cipherbyname : function(const name : PIdAnsiChar): EVP_CIPHER cdecl = nil;
```
Return value has to be **PEVP_CIPHER** instead of EVP_CIPHER. Same mistake at **EVP_get_cipherbynid** wich is based on the upper.

2.
```Delphi
EVP_CipherUpdate : function(ctx : PEVP_CIPHER_CTX; _out : PIdAnsiChar;
		outl : TIdC_INT; _in : PIdAnsiChar; inl : TIdC_INT) : TIdC_INT cdecl = nil;
```
outl has to be **PIdC_INT** instead of TIdC_INT or var parameter.

3.
```Delphi
EVP_CipherFinal_ex: function(ctx : PEVP_CIPHER_CTX; outm : PIdAnsiChar; outl : PIdC_INT) : TIdC_INT;
```
Missing **cdecl = nil**

Greetings :shipit:

**Comment by rlebeau** [comment]
Fixed

**Comment by LFriede** [comment]
Thank you!
