### ISSUE TITLE
Prblm compiling Indy10 with Delphi 2007

### ISSUE THREAD

**Issue by EWalkerDev** [IndySockets/Indy#191]
I have a Delphi 2007 application that I want to use with SgcSockets that requires the latest indy version (Indy 10)

But the indy sources won't compile I will get a E2065 Unsatisfied forward or external declaration '_llmod' in the idZlibHeaders.pas unit

**Comment by rlebeau** [comment]
The `IdZlibHeaders` unit doesn't use `llmod`, so what is the EXACT error message? –

**Comment by EWalkerDev** [comment]
Hi, Remy
 
The exact message is : 
[DCC Error] IdZLibHeaders.pas(1): E2065 Unsatisfied forward or external declaration: '_llmod'
 
I made a binary search and I found a reference to "_llmod" in adler32.obj
 
Regards
Eric Walker
 
> Message du 13/12/17 20:59
> De : "Remy Lebeau" 
> A : "IndySockets/Indy" 
> Copie à : "EWalkerDev" , "Author" 
> Objet : Re: [IndySockets/Indy] Prblm compiling Indy10 with Delphi 2007 (#191)
> 
>
> The IdZlibHeaders unit doesn't use llmod, so what is the EXACT error message? –
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/IndySockets/Indy","title":"IndySockets/Indy","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/IndySockets/Indy"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rlebeau in #191: The `IdZlibHeaders` unit doesn't use `llmod`, so what is the EXACT error message? –"}],"action":{"name":"View Issue","url":"https://github.com/IndySockets/Indy/issues/191#issuecomment-351504913"}}}

**Comment by rlebeau** [comment]
See https://blog.dummzeuch.de/2017/02/01/using_the_adler32_checksum_in_delphi_2007/ for a workaround
