### ISSUE TITLE
missing API and LoadFunctionCLib 

### ISSUE THREAD

**Issue by tothpaul** [IndySockets/Indy#226]
Hello,

I'm working on a Let's Encrypt ACME client; I need the functions BN_num_bits and BN_bn2bin, it's not a big deal, but LoadFunctionCLib is not public in idSSLOpenSSLHeaders so I have to define everything myself.

It could be nice to have a function to load custom functions from OpenSSL.

**Comment by tothpaul** [comment]
there's also a bug on function GetCryptLibHandle : Integer;

it should return a THandle or a HMODULE (Integer is truncated to 32bits under Linux64)

**Comment by rlebeau** [comment]
I already made that change awhile ago in my dev copy of Indy, but it hasn't been checked in yet.
