### ISSUE TITLE
SMTP Reply Enhanced code handled incorrectly

### ISSUE THREAD

**Issue by need-back** [IndySockets/Indy#251]
Hi,

In IdReplySMTP the TIdSMTPEnhancedCode.AssignTo function set available at last (what is true if valid information available):
`    LE := TIdSMTPEnhancedCode(ADest);`
`    LE.StatusClass := FStatusClass;`
`    LE.Subject := FSubject;`
`    LE.Details := FDetails;`
`    LE.Available := FAvailable;`   <- at this point the setter below will called

, but TIdSMTPEnhancedCode.SetAvailable reset other properties if value is true:
`    if AValue then`
`    begin`
`      FStatusClass := CLASS_DEF;`
`      FSubject := NODETAILS;`
`      FDetails := NODETAILS;`
`    end;`

I suggest to reverse the condition in SetAvailable to clear if value false:
`    if not AValue then`

Best Regards,
Needback

**Comment by rlebeau** [comment]
Fixed in SVN rev 5496
