### ISSUE TITLE
Add macos64 bits support

### ISSUE THREAD

**Issue by nostroyo** [IndySockets/Indy#264]
The latest delphi beta introduce macOS 64 with some change on Indy. Could you add it to your repo?

**Comment by rlebeau** [comment]
I was not aware that any changes had been made to Indy.  What changes were made exactly?

**Comment by nostroyo** [comment]
You can find attached the diff.
[Apply_Embarcadero_changes_to_support_OSX64.txt](https://github.com/IndySockets/Indy/files/3328766/Apply_Embarcadero_changes_to_support_OSX64.txt)
