### ISSUE TITLE
App freeze when network goes down

### ISSUE THREAD

**Issue by souch** [IndySockets/Indy#271]
Since the commit #d54269ed3817e4d29023673aa3d78781ac826465, when network is unplugged, on Linux, our whole application gets frozen. We are using FMX.

The culprit lines in the commit are near line 2930 of IdSSLOpenSSL.pas : 
```      
if (fSSLSocket <> nil) and (fSSLSocket.fSSL <> nil) then begin
  // if SSL_shutdown() returns 0, a "close notify" was sent to the peer and SSL_shutdown()
  // needs to be called again to receive the peer's "close notify" in response...
  if SSL_shutdown(fSSLSocket.fSSL) = 0 then begin
    SSL_shutdown(fSSLSocket.fSSL);
  end;
end;
```

If I comment these lines, the app do not freeze anymore if I unplug the cable.

**Comment by rlebeau** [comment]
Those lines are required to fix an SSL/TLS issue in TIdFTP (see [this discussion](https://www.atozed.com/forums/thread-1187-post-3806.html)), so removing them will break TIdFTP again.  Have you tried assigning a timeout on the underlying socket to avoid SSL_shutdown() hanging when the network is not available?
