### ISSUE TITLE
IdIMAP4Server.pas compile error (Delphi <=XE2)

### ISSUE THREAD

**Issue by megamurmulis** [IndySockets/Indy#283]
File: `/Lib/Protocols/IdIMAP4Server.pas`, Line: `730`
```
var
  LStart: Int64;
  LN: Int64;
  LEnd: Int64;
  ..
	for LN := LStart to LEnd do begin
	  AMessageNumbers.Add(IntToStr(LN));
	end;
```
As these variables are Int64 - will fail to compile on Delphi <=XE2 (possibly later too; but works XE8+):<br>
`[Error] IdIMAP4Server.pas(730): For loop control variable must have ordinal type`.<br>
It could be replaced with `while` loop - something like:
```
	LN := LStart;
	while LN <= LEnd do begin
		AMessageNumbers.Add(IntToStr(LN));
		Inc(LN);
	end;
```

**Comment by rlebeau** [comment]
It was XE8 that first introduced support for using `Int64` as a `for` loop counter.
