### ISSUE TITLE
Packages for Delphi 10.3 missing?

### ISSUE THREAD

**Issue by Athris** [IndySockets/Indy#285]
Hello!

I download the github build as zip archiv, but i don't find the 260 packages for Delphi 10.3 Rio:
IndySystem260, IndyCore260, IndyProtocols260, dclIndyCore260, dclIndyProtocols260

**Comment by rlebeau** [comment]
I have now added project files for 10.3 Rio.  Some of the `.dproj` and `.res` files are missing, because I don't actually have 10.3 installed to create them, but those should get generated automatically as needed.  If you'd like to submit the missing files after compiling Indy, I will add them.

**Comment by rlebeau** [comment]
I have checked in some `.dproj` files for 10.3 now.
