### ISSUE TITLE
E2280: Unterminated conditional directive

### ISSUE THREAD

**Issue by StephenB4431** [IndySockets/Indy#288]
Introduced in commit 5d7646b9bb9f19ccda9809851b2a9b62d6cdf911 - "\Indy\Lib\Protocols\IdCompilerDefines.inc(1361) Fatal: E2280 Unterminated conditional directive"
The new {$IFDEF HAS_UNIT_UnixType} doesn't appear to have a corresponding {$ENDIF}, this looks like it affects:
Lib/Core/IdCompilerDefines.inc
Lib/FCL/IdCompilerDefines.inc
Lib/Protocols/IdCompilerDefines.inc
Lib/SuperCore/IdCompilerDefines.inc
Lib/System/IdCompilerDefines.inc

**Comment by ezurschmiede** [comment]
Guten Tag,

vielen Dank für Ihre E-Mail.

Ich bin bis am 13.3.2020 ausser Haus. Die eingehenden E-Mails werden während dieser Zeit nur sporadisch bearbeitet.

Wenn es kein persönliches Anliegen ist, wenden Sie sich doch bitte an support@delight.ch oder an info@delight.ch

Schöne Grüsse
Elias Zurschmiede

delight software gmbh

**Comment by rlebeau** [comment]
The directive was supposed to be a {$DEFINE} rather than an {$IFDEF}.  This has been fixed now.
