### ISSUE TITLE
Actual Build Version is missing in IdVers.inc

### ISSUE THREAD

**Issue by TGrusche** [IndySockets/Indy#292]
Hi, after moving to github the actual build version in IdVers.inc is missing like you had it in the former builds on indy.fulgan.com.
It would be nice to have it back because it is the simpliest way to check which version on uses.

**Comment by rlebeau** [comment]
Yes, we are aware of this.  GitHub doesn't really have the same kind of automated build numbering like SVN does via revision numbers, unless you use [GitHub's SVN interface](https://help.github.com/en/github/importing-your-projects-to-github/support-for-subversion-clients).  Commits are identified by SHA-1 hashes instead.

I don't have a solution to this issue at this time, short of using manual build numbers on every commit, which I would like to avoid.

In SVN, we have post-commit and post-update hook scripts for TortoiseSVN to populate source files with the revision number via the SubWCRev app.  TortoiseGIT has similar hooks and a GitWCRev app.  I'll have to see if it exposes anything we can use for versioning.

**Comment by bennybechdk** [comment]
maybe https://gitversion.net/docs/ can help.
PreReleaseNumber and CommitsSinceVersionSource gives a SVN like revisionnumber.

**Comment by rlebeau** [comment]
I don't think that will help:

"GitVersion is a tool to help you achieve _Semantic Versioning_ on your project."

Indy does not use Semantic Versioning at this time.

"The Semantic Version does not increment every commit. This trips a lot of people up, by default GitVersion does not increment the SemVer every commit. This means that you will get multiple builds producing the same version of your application."

Indy's build version was based on it being incremented on every commit.

**Comment by zedxxx** [comment]
Maybe, git hooks + `git rev-list HEAD --count` can be used?

**Comment by rlebeau** [comment]
I will likely end up making an actual GitHub release for Indy 10 in the hopefully-near future and start it at 10.6.3 going forward.  Then I will be able to just update `IdVers.inc` manually for the time being until Indy 11 can switch to actual Semantic Versioning and I'll consider using something like GitVersion for managing that.

**Comment by rlebeau** [comment]
> I will likely end up making an actual GitHub release for Indy 10 in the hopefully-near future and start it at 10.6.3 going forward. Then I will be able to just update `IdVers.inc` manually for the time being

This is now been implemented.  Closing this ticket.
