### ISSUE TITLE
Fatal: Cannot find IdSync used by XXX

### ISSUE THREAD

**Issue by D3lphi3r** [IndySockets/Indy#307]
Lazarus => Indy installed by OPM

When adding IdSync unit to project, The IDE complain with "cannot find IdSync" after compile.

Solution adding IdSync unit to indylaz Package manually.

**Comment by rlebeau** [comment]
Known issue in the FreePascal/Lazarus community:

https://forum.lazarus.freepascal.org/index.php?topic=41888.0

https://forum.lazarus.freepascal.org/index.php/topic,20782.msg178791.html#msg178791

Although IndyLaz is a part of Indy, we don't maintain Indy in OPM.  You should contact GetMem in [this thread](https://forum.lazarus.freepascal.org/index.php/topic,34297.0.html) in the Lazarus forums, he handles that.
