### ISSUE TITLE
sslv3 alert handshake failure in some websites https (AWS)

### ISSUE THREAD

**Issue by emilianoveiga** [IndySockets/Indy#309]
when using TIdHttpClient and IdSSLIOHandlerSocketOpenSSL to connect and download file on some https:// address, I got the exception error:

First chance exception at $74DB4402. Exception class EIdOSSLUnderlyingCryptoError with message
'Error connecting with SSL. error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'.

As I tested, this happen with some webservers running on AWS.

The Indy version used was compiled from last branch /OpenSSL-1.1.x commit

**Comment by rlebeau** [comment]
I have not done any kind of review of the 1.1.x branch code yet, so I can't state whether it is working or not.  Do you have the same failure if you use the main trunk code with OpenSSL 1.0.2?  Are you trying to connect to the server that _requires_ OpenSSL 1.1.x and TLS 1.3?

**Comment by emilianoveiga** [comment]
yes, the failure occurs with both versions. The server is also compatilbe with Openssl 1.0.x. I'll sniffer connection using WireShark and update this issue soon. Thank you for attention and support.
The code is simple download test from https URL.

`   TMemoryStream *ms = new TMemoryStream();
   ms = new TMemoryStream();
 try
 {
   IdHTTP1->IOHandler = IdSSLIOHandlerSocketOpenSSL1;
   IdHTTP1->Get("https://URL",ms);

 }
 catch(Exception &e)
 {
   MessageDlg("Failed: " + e.Message,
		mtWarning, TMsgDlgButtons() << mbOK, 0);
 }`

**Comment by rlebeau** [comment]
What do your settings for the `SSLIOHandler` look like?  Particularly its `SSLOptions->SSLVersion` property?  By default, it is set to TLS 1.0 only (see https://github.com/IndySockets/Indy/issues/181), which many servers are now phasing out.  Do you have the same problem with TLS 1.1 and 1.2 enabled?

**Comment by emilianoveiga** [comment]
I tested variation in SSLIOHandler configs. The currently SSLIOHandler settings is set to:
- Method: sslvSSLv23
- Mode: sslmUnassigned
- SSLVersions: [sslvSSLv2,sslvSSLv3,sslvTLSv1,sslvTLSv1_1,sslvTLSv1_2]

I've checked some URLs using openssl command testing versions of TLS; tls1, tls1_2
>openssl _sclient -connect URL:443 -tls1_2

And confirmed that the issue is on AWS server side which should acept tls1_2 minimum, but some hosts are using only tls1_3. 

Thus, this issue can be closed

Thank you.

**Comment by rlebeau** [comment]
>SSLVersions: [sslvSSLv2,sslvSSLv3,sslvTLSv1,sslvTLSv1_1,sslvTLSv1_2]

Do not use `sslvSSLv2` (SSL v2.0) and `sslvSSLv3` (SSL v3.0) at all.  They are no longer secure, nobody uses them anymore.  Use only sslvTLSv1 (TLS v1.0) and higher.

> And confirmed that the issue is on AWS server side which should acept tls1_2 minimum, but **some hosts are using only tls1_3**.

That is an important detail.  `TIdSSLIOHandlerSocketOpenSSL` does not support TLS 1.3 at this time, as that requires OpenSSL 1.1.x, but `TIdSSLIOHandlerSocketOpenSSL` supports only up to OpenSSL 1.0.2.

However, there is currently a branch available that provides a new experimental SSLIOHandler for OpenSSL 1.1.x with support for TLS 1.3.  See the discussion in https://github.com/IndySockets/Indy/issues/183.  There is a pull request attached to that ticket.  You can download that code and see if it helps you.

**Comment by emilianoveiga** [comment]
Thanks for information. I'll follow #183 and make new tests. Meanwhile my demand was a simple file to download I solved using only http. Also, I think there is some misconfiguration at webserver running on EC2 AWS machine that I need to check, although the browsers can acces and download from https.
