### ISSUE TITLE
Error sending file with TIdFTP on Android in Delphi 10.3

### ISSUE THREAD

**Issue by Denercy** [IndySockets/Indy#316]
The server does not avoid the return response, or the client is unable to receive the response and freezes the application, giving a read timeout error after a few seconds. Sometimes the file is sent even with an error, sometimes not.

**Comment by ezurschmiede** [comment]
Guten Tag,

vielen Dank für Ihre E-Mail.

Ich bin bis am 3.8.2020 in den Sommerferien. Die eingehenden E-Mails werden während dieser Zeit nicht bearbeitet.

Wenn es kein persönliches Anliegen ist, wenden Sie sich doch bitte an support@delight.ch oder an info@delight.ch

Schöne Grüsse
Elias Zurschmiede

delight software gmbh

**Comment by rlebeau** [comment]
The FTP protocol uses multiple TCP connections.  By default, the `TIdFTP.Passive` property is set to false to use active-mode file transfers.  This means that the FTP server will make outgoing TCP connections to the FTP client for transfers, which is not likely to work well on mobile devices, where cellular providers to do not allow customers to run their own TCP servers on their network.

Try setting the `TIdFTP.Passive` property to true to use passive-mode connections instead.  This means that the FTP client will make outgoing TCP connections to the FTP server for transfers.

Also, make sure that you are using an up-to-date version of Indy, as there was recently an update made to `TIdFTP` to fix #300, which may or may not be related to your issue, too.  This fix is not in the version of Indy that shipped pre-installed in 10.3.

**Comment by Denercy** [comment]
Good night. Thank you for your quick response.
Please, where can I find the update download for the Indy components for Delphy 10.3?
I tried but I didn't find it.
thankful

**Comment by rlebeau** [comment]
There is no "update download" for 10.3.  You will need to uninstall Indy from the IDE, and then download the latest source code from the trunk of Indy's GitHub repo and recompile it in 10.3, per Indy's [installation instructions](http://ww2.indyproject.org/Sockets/Docs/Indy10Installation.EN.aspx).

**Comment by Denercy** [comment]
Hello Remy.

Thnak you for your answer.

Denercy

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Remy Lebeau<mailto:notifications@github.com>
Enviado:segunda-feira, 27 de julho de 2020 14:19
Para: IndySockets/Indy<mailto:Indy@noreply.github.com>
Cc:Denercy<mailto:dionisio.denercy@outlook.com>; Comment<mailto:comment@noreply.github.com>
Assunto: Re: [IndySockets/Indy] Error sending file with TIdFTP on Android in Delphi 10.3 (#316)


There is no "update download" for 10.3. You will need to uninstall Indy from the IDE, and then download the latest source code from the trunk of Indy's GitHub repo and recompile it in 10.3, per Indy's installation instructions<https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fww2.indyproject.org%2FSockets%2FDocs%2FIndy10Installation.EN.aspx&data=02%7C01%7C%7C56bc31c8b8f048f5655f08d832513acf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637314671736279301&sdata=rZh6yi2Z2uGr6ba7iSQSZwtwbHAlgMffGr%2BlxNkqLgQ%3D&reserved=0>.
