### ISSUE TITLE
Support cookie property SameSite

### ISSUE THREAD

**Issue by zencode1** [IndySockets/Indy#320]
The SameSite cookie property was introduced in 2019 and is now required for cross-scripting support in Chrome.  Firefox and Edge indicated they may require at some point in the future.  To support this new property, TIdCookie can be modified in one of these suggested ways (others may exist):
1. Natively process SameSite (same as HttpOnly, Secure, etc)
2. Allow custom property processing (read/write) by a descendant class
3. Allow the application to read/write custom properties to TIdCookie

**Comment by fastbike** [comment]
Great, look forward to this being available

**Comment by rlebeau** [comment]
See the [cookie-samesite branch](https://github.com/IndySockets/Indy/tree/cookie-samesite) in the repo

**Comment by rlebeau** [comment]
The `cookie-samesite` branch has now been merged into master
