### ISSUE TITLE
Indy Releases and versioning

### ISSUE THREAD

**Issue by vincentparrett** [IndySockets/Indy#328]
Right now Indy lacks actual releases.. there's just what's in the repo and that is constantly evolving (as it should). That makes traceability etc difficult. 

I'm sure many people just use the version shipped with delphi, but I never do, because I have no idea which actual version it is they are shipping, and since they rarely (if ever) update it until the next major release. 

I think GitVersion - https://gitversion.net/docs/ - is ideally suited to this sort of project. It does require some process changes though that does take some time to get your head around - I recommend watching this presentation - https://www.youtube.com/watch?v=SlM02V1tkSc  as it explains both gitversion and gitreleasemanager very well. 
 
I'm working on using gitversion on my open source projects (once I finish adding gitversion support to FinalBuilder and Continua CI).  

One of my motivations for wanting Indy releases is to make it possible to support Indy in the package manager I am working on ( https://github.com/DelphiPackageManager/DPM ) - packages need a version, and I'm using semantic versioning for packages (as do most other package managers for other eco systems).  

I have created the package spec files for Indy and am building the packages here on a clone, but the package versions are meaningless since Indy currently doesn't really have any actual published releases. 

I'd be willing to help out with this.

**Comment by rlebeau** [comment]
Related: https://github.com/IndySockets/Indy/issues/292

**Comment by wolfgangbures** [comment]
I agree with @vincentparrett , for non-github users (like me) it might be impossible to find a "current" version to download. (This is actually how I found this thread).
An actual released version would make things easier! Or maybe a WIKI entry on "How do I get the recent version of indy?"? :-)

**Comment by rlebeau** [comment]
I will likely end up making an actual GitHub release for Indy 10 in the hopefully-near future and start it at 10.6.3 going forward.  Then Indy 11 can switch to actual Semantic Versioning and I'll consider using something like GitVersion for managing that.

**Comment by rlebeau** [comment]
Alternatively, consider [Calendar Versioning](https://calver.org) instead? See [Designing a version](https://sedimental.org/designing_a_version.html).

Something like `YYYY.0M.patch` ("Indy 2023.04.1") or `YY.MM.patch` ("Indy 23.4.1").

Or, maybe a mix of Semantic and Calendar versioning? Perhaps Semantic Versioning with a Calendar component, ie: `<major>.<minor>.YYYYMMDD` ("Indy 10.6.20230430", "Indy 11.0.20240101", etc), or vice versa, ie: `YYYY.<major>.<minor>` ("Indy 2023.1.1", "Indy 2024.1.1", etc).

Indy has been stuck at 10.6.2.x since 2015, and #292 only made it worse. Need to decide on something and finally get it working.

**Comment by vincentparrett** [comment]
I still prefer [Semantic Versioning](https://semver.org/) because it has a very clear definition with regards to compatibility etc.

**Comment by rlebeau** [comment]
> I will likely end up making an actual GitHub release for Indy 10 in the hopefully-near future and start it at 10.6.3 going forward for subsequent releases.

This is now been implemented. For the time being, version numbers in `IdVers.inc` and package resources will be updated manually on each release. Closing this ticket.
