### ISSUE TITLE
D2007 - IdIOHandlerStack - E1012 Constant expression violates subrange bounds

### ISSUE THREAD

**Issue by StephenB4431** [IndySockets/Indy#334]
In Delphi 2007 - IdIOHandlerStack line 248:
`if E.LastError in [Id_WSAESHUTDOWN, Id_WSAECONNABORTED, Id_WSAECONNRESET] then begin`
This line gives a "Constant expression violates subrange bounds" error (Id_* consts are over 255).

Changing it to 
`if (E.LastError = Id_WSAESHUTDOWN) or (E.LastError = Id_WSAECONNABORTED) or (E.LastError = Id_WSAECONNRESET)  then begin` resolves it.

**Comment by ezurschmiede** [comment]
Guten Tag,

vielen Dank für Ihre E-Mail.

Ich bin bis am 8.2.2021 in den Skiferien. Die eingehenden E-Mails werden während dieser Zeit nicht bearbeitet. Für Support schreiben Sie bitte an support@delight.ch

Schöne Grüsse
Elias Zurschmiede

delight software gmbh
