### ISSUE TITLE
XMPP Support.

### ISSUE THREAD

**Issue by el3ctr0lyte** [IndySockets/Indy#340]
I have no idea how much this is to ask, but would you consider adding XMPP support. I understand that a server implementation with all the appropriate features is gonna be one tough job, but maybe a client with just messages support?

I'd also like to say, Thank you for the amazing work you do! This is one of the best open source projects i have ever seen, and i don't know what i'd do without it.

**Comment by rlebeau** [comment]
FmxExpress has posted [Instant Messaging Demo Client And XMPP Component For Delphi XE6 Firemonkey On Android And IOS](https://www.fmxexpress.com/instant-messaging-demo-client-and-xmpp-component-for-delphi-xe6-firemonkey-on-andoid-and-ios/), which uses Indy for its sockets.  Maybe use that as a base for a future implementation.

**Comment by rlebeau** [comment]
Duplicate of #146
