### ISSUE TITLE
How do you upgrade or install newest indy packages

### ISSUE THREAD

**Issue by RogelioGaytan** [IndySockets/Indy#347]
Hello 

   I'm new to delphi indy library, ihave to use Delphi 2007 wich comes with indy 10.1.

   I want to upgrade to latest indy version.

How can i achieve that?

**Comment by rlebeau** [comment]
Download the `/Lib` source folder from Indy's GitHub repo at https://github.com/IndySockets/Indy/, and then follow the [installation instructions](https://web.archive.org/web/20200925081341/http://ww2.indyproject.org/Sockets/Docs/Indy10Installation.EN.aspx) (archived copy).

**Comment by RogelioGaytan** [comment]
thank you for pointng me to the right direction
