### ISSUE TITLE
TIdConnectThroughHttpProxy uses HTTP 1.0, while the request comes from browser using HTTP 1.1

### ISSUE THREAD

**Issue by realbitt** [IndySockets/Indy#348]
https://github.com/IndySockets/Indy/blob/a525e99357d7f3d0a98988df7d0104c572e7e02c/Lib/Protocols/IdConnectThroughHttpProxy.pas#L107

**Comment by rlebeau** [comment]
Yes, `TIdConnectThroughHttpProxy` is hard-coded to use HTTP 1.0 when sending a `CONNECT` request to an HTTP proxy. What is the problem with that, exactly?  There should be no real semantic difference in how `CONNECT` behaves in HTTP 1.0 vs 1.1.  And besides, `TIdConnectThroughHttpProxy` is not intended to be used for proxying HTTP connections anyway, `TIdHTTP` has its own built-in proxy support for that purpose.  `TIdConnectThroughHttpProxy` is meant for proxying non-HTTP connections through an HTTP proxy.  So it shouldn't really matter which HTTP version is used for the communication with the proxy itself.  Once that connection has been established, any data between the client and the target server is arbitrary.

**Comment by realbitt** [comment]
I built proxy server application, all browser request passes thro my proxyServer but in a lot of cases browser throws error in console 
**ERR_HTTP2_PROTOCOL_ERROR** so I think this error is related with http version inside TIdConnectThroughHttpProxy when forward connection.

if not, please can you help me why error raised when using proxyserver using indy ?

**Comment by rlebeau** [comment]
> browser throws error in console ERR_HTTP2_PROTOCOL_ERROR

I already addressed that in your [StackOverflow question](https://stackoverflow.com/questions/68098711/) about that issue.  `TIdHTTPProxyServer` does not support HTTP/2 at this time (https://github.com/IndySockets/Indy/issues/163).
