### ISSUE TITLE
IdHash.pas does not compile in .NET

### ISSUE THREAD

**Issue by rlebeau** [IndySockets/Indy#36]
IdHash.pas does not compile in .NET:
  
```
[DCC Error] IdHash.pas(381): E2003 Undeclared identifier: 'TransformFinalBlock'
[DCC Error] IdHash.pas(382): E2003 Undeclared identifier: 'Hash'
[DCC Error] IdHash.pas(451): E2003 Undeclared identifier: 'TransformBlock'
```  
Offhand, it looks like the TIdHashIntCtx type was intended to be an alias for the .NET HashAlgorithm class, but it is not actually declared that way. TIdHashIntCtx is an alias for an IntPtr instead.

**Comment by czhower** [comment]
Are we still supporting .NET?

**Comment by rlebeau** [comment]
No.  Right now, I'm just porting existing issues over from CodePlex, and I'm marking the issues that will be addressed in the upcoming maintenance release.
