### ISSUE TITLE
Error in latest IdIOHandler.

### ISSUE THREAD

**Issue by ijbranch** [IndySockets/Indy#361]
Just downloaded Indy 10 rev 3902.

D10.4.2, Win 10.

When building my project I get an error in IdIOHandler..

`function TIdIOHandler.ReadInt16(AConvert: Boolean = True): Int16;
begin
  EnsureInputBytes(Self, SizeOf(Int16));			<<   Error here..
  Result := Int16(InputBuffer.ExtractToUInt16(-1, AConvert));
end;`

The error is..
"[dcc32 Error] IdIOHandler.pas(1285): E2010 Incompatible types: 'Integer' and 'TIdIOHandler'"

 

Regards,

Ian

**Comment by rlebeau** [comment]
Fixed

**Comment by ijbranch** [comment]
Fix Confirmed/Verified.
Tks Remy.
