### ISSUE TITLE
Extending TIdStackLocalAddress with 'Description: string' property to use WinAPI Interface Description

### ISSUE THREAD

**Issue by Hugie** [IndySockets/Indy#383]
Hi Indy Team,

we would love to extend the TIdStackLocalAddress Class with a Description Property to be able to store the Windows Interface Description, e.g. "Realtek PCIe GbE Family Controller" to be able to present this Information in an Application.

Without it, we would need to fetch this Information again through the API. 
Since the Information is fetched anyway in GetLocalAddressesByAdaptersAddresses in IdStackWindows.pas:1388 through the GetAdaptersAddresses, it would be wise to use this Information directly.

The alternative is to present the user the "TIdStackLocalAddressAccess.InterfaceName" property, which - in Windows - is only a GUID similar to "123456-123123-12345-12123", which does not help identifying it in a GUI or Logfile.

I will create a PR with our suggestion and would be happy for comments - or if you could accept it ;)

Best regards and thank you for your work.

**Comment by rlebeau** [comment]
`GetAdaptersAddresses()` can output both a `Description` and a `FriendlyName` (though currently, the `GAA_FLAG_SKIP_FRIENDLY_NAME` flag is being used). Would it be worth adding both?
