### ISSUE TITLE
NTPToDateTime wrong for two days after DST change

### ISSUE THREAD

**Issue by BoIitos** [IndySockets/Indy#386]
#333 introduced a bug in `TIdSNTP.NTPToDateTime()`. The two day offset needs to be applied before passing it to `UTCTimeToLocalTime()`, otherwise the distinction between DST and standard time will be two days off (e.g. on 2021-11-01 it will return DST because it evaluates using 2121-10-30). 

Instead of 
`Result := UTCTimeToLocalTime((Value1 + Value2) / 86400) + 2;`
it should be something like
`Result := UTCTimeToLocalTime((Value1 + Value2 + 2*86400) / 86400);`

**Comment by rlebeau** [comment]
The original code before #333 was applied looked like this:
```
Result := ((Value1 + Value2) / 86400) - TimeZoneBias + 2;
```
Looking at it again, I suppose that could also be written as:
```
Result := ((Value1 + Value2) / 86400) + 2 - TimeZoneBias;
```
In which case, I think the correct code should look like this instead:
```
Result := UTCTimeToLocalTime(((Value1 + Value2) / 86400) + 2);
```

Also, does this mean the calculation in `TIdSNTP.DateTimeToNTP()` is wrong, too?  Before #333, it was originally:
```
Value1 := (ADateTime + TimeZoneBias - 2) * 86400;
```
But is now:
```
Value1 := (LocalTimeToUTCTime(ADateTime) - 2) * 86400;
```
Should it be this instead?
```
Value1 := (LocalTimeToUTCTime(ADateTime - 2)) * 86400;
```

**Comment by BoIitos** [comment]
> In which case, I think the correct code should look like this instead:
> Result := UTCTimeToLocalTime(((Value1 + Value2) / 86400) + 2);

This should be equal to my formula but is better readable.

> Value1 := (LocalTimeToUTCTime(ADateTime) - 2) * 86400;
> Should it be this instead?
> Value1 := (LocalTimeToUTCTime(ADateTime - 2)) * 86400;

LocalTimeToUTCTime needs a TDateTime based on 1899-12-30. Therefore the two-day modifier for NTP base date 1900-01-01 needs to be applied outside here.

**Comment by rlebeau** [comment]
Did the commited fix solve your issue?

**Comment by BoIitos** [comment]
Yes, the commit fixed the issue.
