### ISSUE TITLE
Cannot send TMemoryStream from TIdTCPClient to TIdTCPServer

### ISSUE THREAD

**Issue by highlysceptical** [IndySockets/Indy#402]
I have a very simple Indy client / server setup, which works fine when I use IOHandler.WriteLn to send strings.

However, I have tried to use IOHandler.Write procedure (see sample code below) following the various examples on the Internet, but no matter what I do, the TIDTCPServer.OnExecute procedure does not fire, so on the face of it, no data is actually being sent to the server.

I am using Indy 10.6.2.5366 components.

Can anyone suggest what I might be doing wrong?

> with IDClient do
      begin
        msRecInfo := TMemoryStream.Create;
        MyData := 'some data';
        msRecInfo.Write(MyData, SizeOf(MyData));
        msRecInfo.Position := 0;
        IOHandler.Write(msRecInfo, 0, True);
        msRecInfo.Free;
    end;

**Comment by highlysceptical** [comment]
Thanks for your comments.

Originally, MyData was a record.  I only changed it to a string as an experiment, since i knew I could successfully send a string using the WriteLn procedure.  I hadn't appreciated I couldn't send a string in the same way.

I am puzzled about the firing continuously comments.  If I use WriteLn() to write strings, the server OnExecute() event appears to fire each time it receives data - I have a breakpoint on the first line of the code and it only breaks the execution when I call WriteLn() from the client.

I would show you my code, but it isn't in a presentable form at present, as I was just trying to cobble something together.  I assumed that since the breakpoint works on the server whenever I call WriteLn() on the client, it would also work every time I call Write() from the client.   Since it isn't doing, I assumed the problem was client side.  

I will do a bit more work on it and put together what I am actually trying to achieve, and if it still doesn't work, I will post the actual code for both client and server.

**Comment by jachguate** [comment]
Remy comment about it firing in a continuously is right. Since you say the method looks to fire each time you write a new string, I assume you're reading just a string in the method code, but you can try to read only one byte at a time, and you'll see the event firing and firing again.

**Comment by highlysceptical** [comment]
Thanks for all the information.  I am still trying to get my head around the firing continuously bit.  But I have now managed to update my code so that it works!

Thanks again.

**Comment by rlebeau** [comment]
> Remy comment about it firing in a continuously is right. Since you say the method looks to fire each time you write a new string, I assume you're reading just a string in the method code, but you can try to read only one byte at a time, and you'll see the event firing and firing again.

Reading 1 byte at a time is not really a good validation of the event firing continuously.  A better validation would be to not read anything at all, simply `Exit` from the event handler immediately (or at least `Sleep()` before `Exit`, so you don't thrash the CPU).

**Comment by highlysceptical** [comment]
Remy.  I don't understand your comment about thrashing the CPU.  If the event is firing continuously anyway, how can my code thrash the CPU.

I suspect I  haven't understood the mechanics of how this works yet.  Is there a demo program anywhere that would help me understand?

**Comment by highlysceptical** [comment]
Ignore that.  I found the demos on Github.  I am having a play with them now._

**Comment by rlebeau** [comment]
> Remy. I don't understand your comment about thrashing the CPU. If the event is firing continuously anyway, how can my code thrash the CPU.

Calling the event in a tight loop without performing any CPU-yielding operations in between iterations will eat up CPU cycles, starving other threads for CPU time.  Performing normal blocking socket operations will suffice to yield CPU cycles to other threads.  So will sleeping.
