### ISSUE TITLE
error "starttls is required to send mail"

### ISSUE THREAD

**Issue by felipecota** [IndySockets/Indy#406]
I'm trying to use TIdSMTP in Delphi 7 to connect to smtp.office365.com and I'm getting a "starttls is required to send mail" error.

I set
UseTLS: utUseExplicitTLS
host: smtp.office365.com:587 on idSMTP and IdSSLIOHandlerSocketOpenSSL
SSLVersions: only sslvTLSv1_2
mode: sslmClient

Is there anything more I can do?

**Comment by rlebeau** [comment]
Offhand, it looks fine to me.  Using `utUseExplicitTLS` should be sending a `STARTTLS` command.

Delphi 7 is very old, which version of Indy are you using with it?  Are you setting up the `TIdSMTP`/`TIdSSLIOHandlerSocketOpenSSL` properties in code, or in the Object Inspector at design-time?  Can you please show the actual code/DFM?

**Comment by addsuminc** [comment]
Despite being old, confirming that Delphi 7 still works just fine.

Are the latest OpenSSL DLL's in the same folder as the Delphi exe?


Tony Frates


----- Original Message -----
From: Remy Lebeau ***@***.***>
To: IndySockets/Indy ***@***.***>
Cc: Subscribed ***@***.***>
Date: Wed, 13 Apr 2022 15:17:08 -0700
Subject: Re: [IndySockets/Indy] error "starttls is required to send mail" (Issue #406)

> Offhand, it looks fine to me.  Using `utUseExplicitTLS` should be sending a `STARTTLS` command.
> 
> Delphi 7 is very old, which version of Indy are you using with it?  Are you setting up the `TIdSMTP`/`TIdSSLIOHandlerSocketOpenSSL` properties in code, or in the Object Inspector at design-time?  Can you please show the actual code/DFM?
> 
> -- 


-- 
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by felipecota** [comment]
Thank you @rlebeau I made an empty project to try setting up in code, since my original code was mixing it... when I ran I was asked for the libraries like @addsuminc said, I added it to the bin folder of delphi and it worked! I tried setting up the TIdSMTP/TIdSSLIOHandlerSocketOpenSSL properties and it worked too. Now I'm going to search my original code to see what is different and causing that error. I'm using the indy version from this repository. Thank you!

**Comment by rlebeau** [comment]
Ideally, the OpenSSL DLLs (make sue you are using 1.0.2 or earlier, as `TIdSSLIOHandlerSocketOpenSSL` does not support 1.1.x or later) should be placed in the same folder as your app's `.exe` file.  But, if you want to use a different folder, you can call Indy's `IdOpenSSLSetLibPath()` function at app startup. That function is in the `IdSSLOpenSSLHeaders` unit.

In any case, the DLLs are loaded dynamically as needed, and should not affect `TIdSMTP`'s ability to send a `STARTTLS` command to the server, only to perform a SSL/TLS handshake if the command is successful.  So, provided the following conditions are all true, the `STARTTLS` command should always be getting sent:

1. `TIdSMTP.IOHandler` is assigned an `SSLIOHandler` component
2. `TIdSMTP.UseTLS` is set to `utUseExplicitTLS`
3. `SSLIOHandler.PassThrough` is true (ie, an SSL/TLS session is not active)
5. the server supports `STARTTLS` (check `TIdSMTP.Capabilities` after `TIdSMTP.Connect()` - `TIdSMTP.UseEhlo` must be set to true)

Are any of those conditions false when your main app receives the "starttls is required to send mail" error?

If you attach one of Indy's `TIdLog...` components to the TIdSMTP.Intercept` property, you can log the actual SMTP commands/replies being exchanged with the server.  Can you provide that log here?  Obviously, be sure to mask out any sensitive info (hostname, login credentials, etc).

**Comment by felipecota** [comment]
Many thanks @rlebeau for your attention! I don't know what I was doing wrong but I set up the properties again e now it's working on my original code too. I think I was setting up the component in one form and testing on another one. It's a huge and old application with a lot of forms, but thanks to you two now it's working with the latest indy version. Thank you!
