### ISSUE TITLE
Remove used unit WebBroker from IdHTTPWebBrokerBridge.pas

### ISSUE THREAD

**Issue by uros-ahacic** [IndySockets/Indy#434]
[IdHTTPWebBrokerBridge.pas](https://github.com/IndySockets/Indy/blob/0eaaf44cb5fa2ec25e57a5cdfa4edf3c27d70297/Lib/Protocols/IdHTTPWebBrokerBridge.pas#L61) uses unit WebBroker. It seems to compile just fine without it if I comment it out.

The problem is, that Web.WebBroker.pas (part of Delphi RTL) is compiled with the `{$DENYPACKAGEUNIT}` compiler directive, meaning `IdHTTPWebBrokerBridge` cannot be used in a package, just because of the used WebBroker unit.

Is there a reason for this? Can the unit `WebBroker` be removed from the uses section?

**Comment by rlebeau** [comment]
I don't know, as I didn't originally write this unit.  If it compiles fine without `WebBroker` in the `uses` clause, then great.  But that would have to be tested in older IDEs to make sure it still works (or at least to find which is the 1st version that it can be removed from) before committing this change.

**Comment by uros-ahacic** [comment]
I actually tested this in Delphi 7 with Indy that came with it, the unit `WebBroker` is already in the `uses` clause of IdHTTPWebBrokerBridge.pas and it still compiles if I comment it out.
I can also confirm, that it compiles without the unit since (and including) Delphi 10.2 for sure. Between 7 and 10.2 I cannot say, but it seems like the unit was never really needed. What do you think?

**Comment by rlebeau** [comment]
Sounds good to me. I've made the change.
