### ISSUE TITLE
Bug in procedure TIdTFTPServerReceiveFileThread.Run

### ISSUE THREAD

**Issue by ip4max** [IndySockets/Indy#438]
https://github.com/IndySockets/Indy/blob/83a52d1bb01f3b5fc0382404ea4aea28e415b455/Lib/Protocols/IdTrivialFTPServer.pas#L708

If the packet length is (511 - 4) to (511), no end of transmission is detected. (for 512 an additional zero packet is transmitted and the EOT is detected correctly)

should be

`FEOT := (Length(Buffer) - 4) < (FUDPClient.BufferSize - 4);`

**see RFC 783**

2 bytes + 2 bytes + n bytes
| Opcode | Block # | Data |

Figure 5-2: DATA packet

**Comment by rlebeau** [comment]
Is it working now?

**Comment by ip4max** [comment]
Yes, now it works perfectly.
