### ISSUE TITLE
IndySuperCore70.dpk doesn't compile

### ISSUE THREAD

**Issue by SitAnko** [IndySockets/Indy#441]
When installing run-time packages for D7, I followed the documentation but hit some errors when compiling **IndySuperCore70.dpk**, e.g.: **[Error] IdFiber.pas(327): Undeclared identifier: 'IfTrue'** _et al._
I tried implementing **IfTrue, IfFalse, IfNotAssigned** in **IdException.pas** (by looking at Indy's old code) - but that produced further errors, which made me think I wouldn't be able to duct-tape it myself.
Google didn't help much, probably due to D7's age - so posting this as an issue is my last hope.
Kind regards, Sit.

**Comment by rlebeau** [comment]
SuperCore is a dead product.  It is no longer maintained, and is not part of the min Indy library to begin with.  Just ignore it.
