### ISSUE TITLE
RSHL7StatusTimedout (SVN 4421)

### ISSUE THREAD

**Issue by hafedh-trimeche** [IndySockets/Indy#444]
Hello,

please note this error:
[dcc32 Error] IdHL7.pas(1525): E2003 Undeclared identifier: 'RSHL7StatusTimedout'

**Comment by rlebeau** [comment]
Sounds like you pulled only the latest `IdHL7.pas` file and not Indy as a whole. `IdResourceStringsProtocols.pas` was also updated to add `RSHL7StatusTimedout`:

```
RSHL7StatusTimedOut          = 'Timed out waiting for a message';
```
