### ISSUE TITLE
compilation issues during Installation

### ISSUE THREAD

**Issue by iba-saw** [IndySockets/Indy#447]
Hello,
I'm trying to install Indy10 on Delpi7. I loaded it on 01/12/23.
I uninstalled and removed the old version.
I have compiled the libraries in the order given.
The following errors occurred when compiling dclIndyProtocols in Lib\Protocols:

[Error] IdHL7.pas(526): Declaration of '_AddRef' differs from declaration in interface 'IIdQueuedMessage'
[Error] IdHL7.pas(526): Declaration of '_Release' differs from declaration in interface 'IIdQueuedMessage'
[Fatal error] IdRegister.pas(235): Cannot compile used unit 'IdHL7.pas'

How can I fix the errors, or can you help me?

**Comment by rlebeau** [comment]
I have checked in a fix, try it again and see if it works now

**Comment by iba-saw** [comment]
Thanks, that works now.
Another error has occurred.
when installing the dclIndyCore70.dpk and the dclIndyProtocols70.dpk, the following error message was thrown:
The procedure entry point "@idglobal@IndyStrtoInt$qqrx17System@AnsyStringi" was not found in the DLL "c\dp7\Procects\Bpl\dclIndyCore70.bpl".

**Comment by iba-saw** [comment]
@rlebeau 
Hallo Remy,

Another error has occurred.
when installing the dclIndyCore70.dpk and the dclIndyProtocols70.dpk, the following error message was thrown:
The procedure entry point "@idglobal@IndyStrtoInt$qqrx17System@AnsyStringi" was not found in the DLL "c\dp7\Procects\Bpl\dclIndyCore70.bpl".
I can't get any further here, can you help me again or give hints?

**Comment by rlebeau** [comment]
That kind of error typically means that you have another (older) copy of the mentioned BPL somewhere on your search path that is interfering with the (newer) BPL being referred to.  IOW, check your system for older versions of dclIndyCore70.bpl and rename/remove them so the compiler uses the latest version you just compiled.

**Comment by iba-saw** [comment]
Problems solved, reinstalled Delphi, after that it worked.
