### ISSUE TITLE
Warnings when build project in Delphi 7

### ISSUE THREAD

**Issue by GreySerg2** [IndySockets/Indy#463]
In my project in uses section I write **idHttp** and see 4 warnings:

```
[Warning] IdStackWindows.pas(1777): Comparing signed and unsigned types - widened both operands
[Warning] IdStackWindows.pas(1833): Return value of function 'TIdSocketListWindows.GetItem' might be undefined
[Warning] IdIOHandler.pas(2559): Return value of function 'TIdIOHandler.WriteFile' might be undefined
[Warning] IdAuthenticationSSPI.pas(1103): Return value of function 'TCustomSSPIConnectionContext.UpdateAndGenerateReply' might be undefined
```

Can you fix this warnings?

**Comment by rlebeau** [comment]
How does it look now?

**Comment by GreySerg2** [comment]
Remain 1 warning:
[Warning] IdStackWindows.pas(1832): Return value of function 'TIdSocketListWindows.GetItem' might be undefined

**Comment by GreySerg2** [comment]
I wrote in Header - **"Delphi 7"**.

**Comment by GreySerg2** [comment]
If code will raise exception the return value of function will be undefined. The compiler of Delphi 7 write exactly about this. It's very easy to fix, I set result value at the beginning of function.

**Comment by GreySerg2** [comment]
If I call a function with **try..except** and then will be work with result value of function - it will be undefined.

**Comment by rlebeau** [comment]
> If I call a function with **try..except** and then will be work with result value of function - it will be undefined.

If the caller decides to swallow an exception and use an undefined return value, that is the fault of the caller, not the callee.  Even if the callee were to set its `Result` before `raise`'ing the exception, there is no guarantee that the value will reach the caller.  If the caller wants to save the return value to a variable and use it even if an exception is raised, the `except` handler will have to assign a different value to the variable before letting the code move forward, eg:

```
try
  value := DoSomethingAndGetAValue();
except
  value := SomeOtherValue; // <-- here
end;
// use value as needed...
```

**Comment by rlebeau** [comment]
> There should be an IFDEF around the assignment.

I really want to avoid having to do that.

**Comment by rlebeau** [comment]
I decided to go ahead and just `{$IFDEF}` the three values in Delphi 7 and earlier. They will get taken out anyway in Indy 11.

**Comment by GreySerg2** [comment]
Now all is Ok, all warnings are gone in Delphi 7.
