### ISSUE TITLE
TidHttpServer, error:1409E10F:SSL routines:ssl3_write_bytes:bad length

### ISSUE THREAD

**Issue by WeberAndre** [IndySockets/Indy#483]
Hello,
I have to open the same problem for the http server component.
In this case I use OpenSSL 1.0.2u with the old SSL handler.
The response is directly written to the IOHandler during DoRequest handler. As a chunked http response without content length. The response length is up to serval GB...
At our customer our Server is behind a inverse proxy. My chunksize is between 64k and 128k depending on the data.
If I request the data via http get and Wget commandline everything works fine, but the customer uses FME and there the error occurs. In some cases.
I am not sure where to start searching the issue?
The inversproxy? On the clients host with wget?
Any ideas are appreciated...
What may cause this error?

**Comment by WeberAndre** [comment]
Hi Remy,
I will write some sample tomorrow.
The problem may arise through a renegotiate during sending my large response. May be having a look at openssl issue #7757.

**Comment by rlebeau** [comment]
In `TIdHTTPServer`, every request runs in a separate thread, but there can be multiple requests per connection (via HTTP keep-alives), but they have to be processed sequentially, a new request on the same connection cannot be handled until a previous response is complete.  HTTP/2 and later allow multiple requests in flight on the same connection, but Indy does not support HTTP/2 at this time.

**Comment by WeberAndre** [comment]
After more Debugging and Testing - the exception is not the first on the stack - before this exception I get an **EIdOpenSSLAPISSLError** durring **Connection.IOHandler.WriteBufferFlush();** and afterwards durring finalize of my own code the EIdOSSLUnderlyingCryptoError with the message of Topic with bad length.

**Comment by WeberAndre** [comment]
The EIdOpenSSLAPISSLError RetCode property has the value 10060, which means some sockets timeout.

> 10060 | WSAETIMEDOUT | Connection timed out

I thought the 10060 could only happen durring connection, but what goes wrong if this error hits me on the server side, with an established connection?

**Comment by WeberAndre** [comment]
I have got it - so far - the reason for the timeout is this piece of code:

IdOpenSSLIOHandlerClientBase.pas

procedure TIdOpenSSLIOHandlerClientBase.StartSSL;
var
  LTimeout: Integer;
begin
  inherited;
  if PassThrough then
    Exit;
  FTLSSocket := FContext.CreateSocket();

  {$IFDEF WIN32_OR_WIN64}
  if IndyCheckWindowsVersion(6) then
  begin
    // Note: Fix needed to allow SSL_Read and SSL_Write to timeout under
    // Vista+ when connection is dropped
    LTimeout := FReadTimeOut;
    if LTimeout <= 0 then begin
      LTimeout := 30000; // 30 seconds
    end;
    Binding.SetSockOpt(Id_SOL_SOCKET, Id_SO_RCVTIMEO, LTimeout);
    Binding.SetSockOpt(Id_SOL_SOCKET, Id_SO_SNDTIMEO, LTimeout);
  end;
  {$ENDIF}
end;

In my case the client seems to have a very slow connection or slow programm? - so takes sometimes up to 3 minutes! - before a succesful WriteBufferFlush() of the IOHandlers Buffer does complete and return.  
The Client consumes data at 20-50kb/s each so the receive window of the client fill's up - and I'am getting ACK Pakets with a zero size receive window. 

What I'am watching in my log there are several (8-10) WriteBufferFlush() with 100k of data need only 0,3ms, then suddently it rises to 3 minutes, only for this transfer the next serveral sends are in the range of 0,3ms each.  
This must be a kind of TCP Buffering / Receive Window / ACK Problem? So far I know if the receive buffer of the client is filling up - some kind of throttling should happen - so that every new transfer takes a little longer?
(Server and Client are on Windows Systems)

What I do not understand is that the WriteBufferFlush() takes 3 minutes, if the datarate of 50kb/s at the client, the client receive buffer is complete free again in less than a minute. But space for a new 100k of data should be available in less than 5s?

**Comment by WeberAndre** [comment]
I think we can close this issue. It is no real bug, just a timeout which could fixed after connect. The default WriteTimeout of 30s was it in that case too short, after changing to 120s it works since some days. There are still investigations at the network level to find the underlying issue.
