### ISSUE TITLE
IdSNMP: cannot decode oid like this: ....5.1.1.3.3232256472 it reports a negative ....5.1.1.3.-1062711029

### ISSUE THREAD

**Issue by 2b34** [IndySockets/Indy#496]
hi... I've this problem with a mikrotik device that create dynamic OID with large integer (not signed) I guess that in IdASNUtil1 is enough to change the integer Result in a Cardinal...
function ASNDecOIDItem(var Start: Integer; const Buffer: string): integer;
function ASNDecOIDItem(var Start: Integer; const Buffer: string): Cardinal;

**Comment by rlebeau** [comment]
@2b34 I checked in an update, let me know if it works

**Comment by 2b34** [comment]
Ciao. Ok, now it works... 

I'm having some problems setting up my Alexandria env with the new Indy's version, especially with TMS Software packages that can't found  the IndyCore package... error E2202: Required package 'IndyCore'... 

I noticed that not all deleted files from the the Delphis' bin directory has been recreated... 

Deleted "C:\Program Files (x86)\Embarcadero\Studio\22.0\bin\IndyCore280.bpl" 
Deleted "C:\Program Files (x86)\Embarcadero\Studio\22.0\bin\IndyIPClient280.bpl" 
Deleted "C:\Program Files (x86)\Embarcadero\Studio\22.0\bin\IndyIPCommon280.bpl" 
Deleted "C:\Program Files (x86)\Embarcadero\Studio\22.0\bin\IndyIPServer280.bpl" 
Deleted "C:\Program Files (x86)\Embarcadero\Studio\22.0\bin\IndyProtocols280.bpl" 
Deleted "C:\Program Files (x86)\Embarcadero\Studio\22.0\bin\IndySystem280.bpl" 
Deleted "C:\Program Files (x86)\Embarcadero\Studio\22.0\bin\IndyCore280.jdbg" 
Deleted "C:\Program Files (x86)\Embarcadero\Studio\22.0\bin\IndyIPClient280.jdbg" 
Deleted "C:\Program Files (x86)\Embarcadero\Studio\22.0\bin\IndyIPCommon280.jdbg" 
Deleted "C:\Program Files (x86)\Embarcadero\Studio\22.0\bin\IndyIPServer280.jdbg" 
Deleted "C:\Program Files (x86)\Embarcadero\Studio\22.0\bin\IndyProtocols280.jdbg" 
Deleted "C:\Program Files (x86)\Embarcadero\Studio\22.0\bin\IndySystem280.jdbg" 
Deleted "C:\Program Files (x86)\Embarcadero\Studio\22.0\bin\dclIndyCore280.bpl" 
Deleted "C:\Program Files (x86)\Embarcadero\Studio\22.0\bin\dclIndyProtocols280.bpl" 
Deleted "C:\Program Files (x86)\Embarcadero\Studio\22.0\bin\dclIndyCore280.jdbg" 
Deleted "C:\Program Files (x86)\Embarcadero\Studio\22.0\bin\dclIndyProtocols280.jdbg"  

no .jdbg  and only System, Core and Protocols   .bpl

...but IdSNMP is OK.
thanks.

**Comment by rlebeau** [comment]
> I'm having some problems setting up my Alexandria env with the new Indy's version, especially with TMS Software packages that can't found the IndyCore package... error E2202: Required package 'IndyCore'...

Sounds like TMS is compiled against the copy of Indy that ships pre-installed in the IDE.  That copy does not have version numbers in its package names (ie, because Embarcadero tweaks the packages to use LIBSUFFIX).  If you re-install Indy manually then its package names do have version numbers (ie, because LIBSUFFIX is not being used yet), so you will have to recompile TMS, too (and anything else that depends on Indy).

> no .jdbg

Not sure what that is, that is not a native Delphi file.

> and only System, Core and Protocols .bpl

Because those are the actual Indy packages.  The rest are Embarcadero packages that use/wrap Indy.

**Comment by rlebeau** [comment]
Yes, please open a separate ticket for the COUNTER64 issue
