### ISSUE TITLE
Not able to send email using IdSMTP with OAuth2 Token

### ISSUE THREAD

**Issue by varathasiva** [IndySockets/Indy#548]
Hi,

I'm not able to send email using IdSMTP, OAuth2 token using Office365 SMTP.
Getting authentication unsuccessful error.
Please find below code snapshot and help me with this.

```
var
  bUseSSL, bSMTP, bSMTPRelay, IsAuthenticated: boolean;
  sHost, sUserId, sPWD, sFromAddress, sToAddress, sPort, sErrMsg: string;
  iPortPos: integer;
  NameOfSMTPServer: string;
  SMTP: TIdSMTP;
  IdMsgSend: TIdMessage;
  IOHandlerSSL: TIdSSLIOHandlerSocketOpenSSL;
  UserPassProvider: TIdUserPassProvider;
  SASLXOAuth2: TIdSASLXOAuth2;
  SASLLogin: TIdSASLLogin;
  xoauthSASL: TIdSASLListEntry;
begin
  sHost         := edtEmailHost.Text;
  sUserId       := edtSMTPUserId.Text;
  sPWD          := edtSMTPPassword.Text;
  sFromAddress  := edtFromAddress.Text;
  sToAddress    := edtToAddress.Text;
  sUserId       := edtSMTPUserId.Text;
  sPWD          := edtSMTPPassword.Text;
  sToAddress    := 'sivasubramanian.varatharajan@azentio.com';

  SMTP := TIdSMTP.Create(nil);
  IdMsgSend := TIdMessage.Create(nil);
//  SASLXOAuth2   := TIdSASLXOAuth2.Create(SMTP);
  IOHandlerSSL := TIdSSLIOHandlerSocketOpenSSL.Create(nil);

  try

    if sHost = '' then
      sHost  := SMTPServer + ':' + '587';

    bUseSSL     := rbSMTPUseSSLYes.Checked;

    SMTP.Username := FROMAddress;

    iPortPos := Pos(':', sHost);
    if iPortPos <> 0 then begin
      sPort        := Copy(sHost, iPortPos+1, Length(sHost));
      SMTP.Host    := Copy(sHost, 1, iPortPos-1);
    end
    else begin
      if IsAuthenticated
      then sPort    := '587'
      else sPort    := '25';
      SMTP.Host     := sHost;
    end;

    SMTP.Port       := StrToInt(sPort);

    IOHandlerSSL.Destination := SMTPServer + ':' + sPort;
    IOHandlerSSL.Host        := SMTPServer;
    IOHandlerSSL.Port        := StrToInt(sPort);
    IOHandlerSSL.DefaultPort := 0;

    IOHandlerSSL.SSLOptions.Method := sslvTLSv1_2;
    IOHandlerSSL.SSLOptions.Mode   := sslmUnassigned;
    IOHandlerSSL.SSLOptions.VerifyMode  := [];
    IOHandlerSSL.SSLOptions.VerifyDepth := 0;

    SMTP.IOHandler := IOHandlerSSL;
    SMTP.UseTLS := utUseExplicitTLS;

    sAccessToken := GetAccessTocken;

//    SASLLogin        := TIdSASLLogin.Create(SMTP);
    UserPassProvider := TIdUserPassProvider.Create();

//    SASLLogin.UserPassProvider := UserPassProvider;

{    UserPassProvider.Username := FROMAddress;
    UserPassProvider.Password := sAccessToken;   }
//**    UserPassProvider.Password := sPWD;

//**    SMTP.AuthType := satSASL;
    SMTP.AuthType := satSASL;
    SMTP.SASLMechanisms.Clear;
    xoauthSASL := SMTP.SASLMechanisms.Add;

    xoauthSASL.SASL := TIdSASLXOAuth2.Create(nil);
//    TIdSASLXOAuth2(xoauthSASL.SASL).OnGetAccessToken :=  GetAccessTocken;
    TIdSASLXOAuth2(xoauthSASL.SASL).UserPassProvider := UserPassProvider;
    TIdSASLXOAuth2(xoauthSASL.SASL).UserPassProvider.Username := FROMAddress;
    TIdSASLXOAuth2(xoauthSASL.SASL).UserPassProvider.Password := sAccessToken;
//**    SMTP.SASLMechanisms.Add.SASL := SASLXOAuth2;
//**    SMTP.SASLMechanisms.Add.SASL := SASLLogin;
//**    SMTP.ConnectTimeout := 60000;

    IdMsgSend.Encoding := meMIME;
    IdMsgSend.CharSet := 'utf-8';
    IdMsgSend.Date := Now;
    IdMsgSend.ContentType := 'text/html; charset=UTF-8';
    IdMsgSend.From.Address := FROMAddress;  // Your email
    IdMsgSend.Recipients.EmailAddresses := sToAddress;
    IdMsgSend.Subject := 'This is test email';
    IdMsgSend.Body.Text := 'This test email sent by Sample App.';
    try
      SMTP.Connect;
      try
        SMTP.Send(IdMsgSend);
      except
        on E: Exception do
          ShowMessage('Failed to send email.  An error occurred whilst sending: "' + E.Message + '"');
      end;
    finally
      SMTP.Disconnect;
    end;
  finally
    SMTP.Free;
    IdMsgSend.Free;
//    UserPassProvider.Free;
    SASLLogin.Free;
  end;
```

Thanks & Regards
Siva

**Comment by rlebeau** [comment]
The code is using `TIdSASLXOAuth2` correctly. Are you sure your app is registered with Office365 property (ie, using the right scope `https://outlook.office.com/SMTP.Send`, etc)? Are you sure you have a proper access token? Which SMTP host are you trying to log into?

**Comment by varathasiva** [comment]
Hi, Thanks for your quick response, I can be able to get access token and I'm trying to use smtp.office365.com.
        sOAUTH2Command := 'user=' + FROMAddress + #1 + 'auth=Bearer ' + sAccessToken + #1 + #1;
        SMTP.SendCmd('AUTH XOAUTH2 ' + IDEncoder.Encode(sOAUTH2Command));
        SMTP.Authenticate;
        SMTP.Send(IdMsgSend);
I'm not getting any error, getting error in SMTP.Authenticate 'Authentication unsuccessful".
Getting error in IdSASLCollection.pas if ASASL.TryStartAuthenticate in this line.
Please suggest me how to proceed further.

**Comment by varathasiva** [comment]
Hi,
Thanks for your quick response, please correct me the wrong code here.
Yes, app is registered correctly I can be able to get OAuth2 token also, I'm using scope "https://outlook.office365.com/.default" as per Microsoft online docs.

        sOAUTH2Command := 'user=' + FROMAddress + #1 + 'auth=Bearer ' + sAccessToken + #1 + #1;
        SMTP.SendCmd('AUTH XOAUTH2 ' + IDEncoder.Encode(sOAUTH2Command));
//        SMTP.AuthType := satNone;
        SMTP.Authenticate;
        SMTP.Send(IdMsgSend);
Getting error in SMTP.Authenticate, especially getting error in this method.     if ASASL.TryStartAuthenticate(AHost, APort, AProtocolName, S) then begin
      AClient.SendCmd(ACmd + ' ' + String(ASASL.ServiceName) + ' ' + AEncoder.Encode(S), []);//[334, 504]);

Please help me on this.

**Comment by rlebeau** [comment]
> I'm using scope "https://login.microsoftonline.com/.default" as per Microsoft documentation.
 
That is not what Microsoft's documentation says.

[Authenticate an IMAP, POP or SMTP connection using OAuth](https://learn.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth)

> Ensure to specify the full scopes, including Outlook resource URLs, when authorizing your application and requesting an access token.
>
> | Protocol | Permission scope string |
> | -- | -- |
> | IMAP | https://outlook.office.com/IMAP.AccessAsUser.All |
> | POP | https://outlook.office.com/POP.AccessAsUser.All ||
> | **SMTP AUTH** | **https://outlook.office.com/SMTP.Send** |

> ```
> sOAUTH2Command := 'user=' + FROMAddress + #1 + 'auth=Bearer ' + sAccessToken + #1 + #1;
> SMTP.SendCmd('AUTH XOAUTH2 ' + IDEncoder.Encode(sOAUTH2Command));
> SMTP.Authenticate;
>  SMTP.Send(IdMsgSend);
> ```
>
> I'm not getting any error, getting error in SMTP.Authenticate 'Authentication unsuccessful".

Calling `SMTP.Authentication()` after sending an `AUTH` command manually only makes sense if `SMTP.AuthType=satNone`, is that true in your case?  If not, then you can't send multiple `AUTH` commands, if you are using `SMTP.AuthType=satSASL` with `TIdSASLXOAuth2`.

**Comment by varathasiva** [comment]
Hi,

Thanks for your reply, I'm using the code below to get auth token and sending email both way.
Please suggest what is the wrong in my code.

function TSendEmailF.GetAccessTocken: string;
var
  HttpClient: TNetHTTPClient;
  RequestBody: TStringStream;
  Response: IHTTPResponse;
  JsonObj: TJSONObject;
begin
  HttpClient := TNetHTTPClient.Create(nil);
  try
    RequestBody := TStringStream.Create('grant_type=client_credentials&client_id=' + ClientID +
      '&client_secret=' + ClientSecret +
      '&scope=' + Scope, TEncoding.Default);
    try
     //** Response := HttpClient.Post('https://login.microsoftonline.com/' + TenantID + '/oauth2/v2.0/token', RequestBody);
      Response := HttpClient.Post(TokenEndpoint, RequestBody);
      JsonObj := TJSONObject.ParseJSONValue(Response.ContentAsString) as TJSONObject;
      try
        Result := JsonObj.GetValue<string>('access_token');
      finally
        JsonObj.Free;
      end;
    finally
      RequestBody.Free;
    end;
  finally
    HttpClient.Free;
  end;
end;

Below code sends email using manual commands.
===============================

const 
TokenEndpoint = 'https://login.microsoftonline.com/' + TenantID + '/oauth2/token';
Scope = 'https://outlook.office.com/SMTP.send';

var
  bUseSSL, bSMTP, bSMTPRelay, IsAuthenticated: boolean;
  sHost, sUserId, sPWD, sFromAddress, sToAddress, sPort, sErrMsg: string;
  iPortPos: integer;
  NameOfSMTPServer: string;
  SMTP: TIdSMTP;
  IdMsgSend: TIdMessage;
  IOHandlerSSL: TIdSSLIOHandlerSocketOpenSSL;
  UserPassProvider: TIdUserPassProvider;
  IDEncoder:  TIdEncoderMIME;
  sOAUTH2Command: string;
  SASLLogin: TIdSASLLogin;
begin
  sHost         := edtEmailHost.Text;
  sUserId       := edtSMTPUserId.Text;
  sPWD          := edtSMTPPassword.Text;
  sFromAddress  := edtFromAddress.Text;
  sToAddress    := edtToAddress.Text;
  sUserId       := edtSMTPUserId.Text;
  sPWD          := edtSMTPPassword.Text;
  sToAddress    := 'sivasubramanian.varatharajan@azentio.com';

  SMTP := TIdSMTP.Create(nil);
  IdMsgSend := TIdMessage.Create(nil);
  IOHandlerSSL := TIdSSLIOHandlerSocketOpenSSL.Create(nil);
  IDEncoder :=  TIdEncoderMIME.Create(nil);
  try

    if sHost = '' then
      sHost  := SMTPServer + ':' + '587';

    bUseSSL     := rbSMTPUseSSLYes.Checked;

    SMTP.Username := FROMAddress;

    iPortPos := Pos(':', sHost);
    if iPortPos <> 0 then begin
      sPort        := Copy(sHost, iPortPos+1, Length(sHost));
      SMTP.Host    := Copy(sHost, 1, iPortPos-1);
    end
    else begin
      if IsAuthenticated
      then sPort    := '587'
      else sPort    := '25';
      SMTP.Host     := sHost;
    end;

    SMTP.Port       := StrToInt(sPort);

    IOHandlerSSL.Destination := SMTPServer + ':' + sPort;
    IOHandlerSSL.Host        := SMTPServer;
    IOHandlerSSL.Port        := StrToInt(sPort);
    IOHandlerSSL.DefaultPort := 0;

    IOHandlerSSL.SSLOptions.Method := sslvTLSv1_2;
    IOHandlerSSL.SSLOptions.Mode   := sslmUnassigned;
    IOHandlerSSL.SSLOptions.VerifyMode  := [];
    IOHandlerSSL.SSLOptions.VerifyDepth := 0;

    SMTP.IOHandler := IOHandlerSSL;
    SMTP.UseTLS := utUseExplicitTLS;

    sAccessToken := GetAccessTocken;
    SMTP.Username :=  FROMAddress;
//    SMTP.Password :=  sAccessToken;
    SASLLogin        := TIdSASLLogin.Create(SMTP);
    UserPassProvider := TIdUserPassProvider.Create();

    UserPassProvider.Username := FROMAddress;
    UserPassProvider.Password := sAccessToken;

    SASLLogin.UserPassProvider := UserPassProvider;

    SMTP.AuthType := satNone;
//    SMTP.SASLMechanisms.Clear;

    IdMsgSend.Encoding := meMIME;
    IdMsgSend.CharSet := 'utf-8';
    IdMsgSend.Date := Now;
    IdMsgSend.ContentType := 'text/html; charset=UTF-8';
    IdMsgSend.From.Address := FROMAddress;  // Your email
    IdMsgSend.Recipients.EmailAddresses := sToAddress;
    IdMsgSend.Subject := 'This is test email';
    IdMsgSend.Body.Text := 'This test email sent by Sample App.';
    try
      SMTP.Connect;
      try
        sOAUTH2Command := 'user=' + FROMAddress + #1 + 'auth=Bearer ' + sAccessToken + #1 + #1;
        SMTP.SendCmd('AUTH XOAUTH2 ' + IDEncoder.Encode(sOAUTH2Command));
        SMTP.Authenticate;
        SMTP.Send(IdMsgSend);
      except
        on E: Exception do
          ShowMessage('Failed to send email.  An error occurred whilst sending: "' + E.Message + '"');
      end;
    finally
      SMTP.Disconnect;
    end;
  finally
    SMTP.Free;
    IdMsgSend.Free;
    FreeAndNil(IOHandlerSSL);
    FreeAndNil(SASLLogin);
    FreeAndNil(UserPassProvider);
    FreeAndNil(IDEncoder);
  end;

Below code sends email using SASL.
=======================

var
  bUseSSL, bSMTP, bSMTPRelay, IsAuthenticated: boolean;
  sHost, sUserId, sPWD, sFromAddress, sToAddress, sPort, sErrMsg: string;
  iPortPos: integer;
  NameOfSMTPServer: string;
  SMTP: TIdSMTP;
  IdMsgSend: TIdMessage;
  IOHandlerSSL: TIdSSLIOHandlerSocketOpenSSL;
  UserPassProvider: TIdUserPassProvider;
  SASLXOAuth2: TIdSASLXOAuth2;
//**  SASLLogin: TIdSASLLogin;
  xoauthSASL: TIdSASLListEntry;
  IDEncoder:  TIdEncoderMIME;
  sOAUTH2Command: string;
begin
  sHost         := edtEmailHost.Text;
  sUserId       := edtSMTPUserId.Text;
  sPWD          := edtSMTPPassword.Text;
  sFromAddress  := edtFromAddress.Text;
  sToAddress    := edtToAddress.Text;
  sUserId       := edtSMTPUserId.Text;
  sPWD          := edtSMTPPassword.Text;
  sToAddress    := 'sivasubramanian.varatharajan@azentio.com';

  SMTP := TIdSMTP.Create(nil);
  IdMsgSend := TIdMessage.Create(nil);
//  SASLXOAuth2   := TIdSASLXOAuth2.Create(SMTP);
  IOHandlerSSL := TIdSSLIOHandlerSocketOpenSSL.Create(nil);
  IDEncoder :=  TIdEncoderMIME.Create(nil);
  try

    if sHost = '' then
      sHost  := SMTPServer + ':' + '587';

    bUseSSL     := rbSMTPUseSSLYes.Checked;

    SMTP.Username := FROMAddress;

    iPortPos := Pos(':', sHost);
    if iPortPos <> 0 then begin
      sPort        := Copy(sHost, iPortPos+1, Length(sHost));
      SMTP.Host    := Copy(sHost, 1, iPortPos-1);
    end
    else begin
      if IsAuthenticated
      then sPort    := '587'
      else sPort    := '25';
      SMTP.Host     := sHost;
    end;

    SMTP.Port       := StrToInt(sPort);

    IOHandlerSSL.Destination := SMTPServer + ':' + sPort;
    IOHandlerSSL.Host        := SMTPServer;
    IOHandlerSSL.Port        := StrToInt(sPort);
    IOHandlerSSL.DefaultPort := 0;

    IOHandlerSSL.SSLOptions.Method := sslvTLSv1_2;
    IOHandlerSSL.SSLOptions.Mode   := sslmUnassigned;
    IOHandlerSSL.SSLOptions.VerifyMode  := [];
    IOHandlerSSL.SSLOptions.VerifyDepth := 0;

    SMTP.IOHandler := IOHandlerSSL;
    SMTP.UseTLS := utUseExplicitTLS;

    sAccessToken := GetAccessTocken;

    UserPassProvider := TIdUserPassProvider.Create();

    UserPassProvider.Username := FROMAddress;
    UserPassProvider.Password := sAccessToken;

    SMTP.AuthType := satSASL;
    SMTP.SASLMechanisms.Clear;
    xoauthSASL := SMTP.SASLMechanisms.Add;

    xoauthSASL.SASL := TIdSASLXOAuth2.Create(nil);
    TIdSASLXOAuth2(xoauthSASL.SASL).UserPassProvider := UserPassProvider;
    TIdSASLXOAuth2(xoauthSASL.SASL).UserPassProvider.Username := FROMAddress;
    TIdSASLXOAuth2(xoauthSASL.SASL).UserPassProvider.Password := sAccessToken;
    SMTP.SASLMechanisms.Add.SASL := SASLXOAuth2;

    IdMsgSend.Encoding := meMIME;
    IdMsgSend.CharSet := 'utf-8';
    IdMsgSend.Date := Now;
    IdMsgSend.ContentType := 'text/html; charset=UTF-8';
    IdMsgSend.From.Address := FROMAddress;  // Your email
    IdMsgSend.Recipients.EmailAddresses := sToAddress;
    IdMsgSend.Subject := 'This is test email';
    IdMsgSend.Body.Text := 'This test email sent by Sample App.';
    try
      SMTP.Connect;
      try
        SMTP.Send(IdMsgSend);
      except
        on E: Exception do
          ShowMessage('Failed to send email.  An error occurred whilst sending: "' + E.Message + '"');
      end;
    finally
      SMTP.Disconnect;
    end;
  finally
    FreeAndNil(UserPassProvider);
    FreeAndNil(SASLXOAuth2);
    FreeAndNil(IDEncoder);
    SMTP.Free;
    IdMsgSend.Free;
  end;

Thanks & Regards
Siva

**Comment by rlebeau** [comment]
> Thanks for your reply, I'm using the code below to get auth token and sending email both way. Please suggest what is the wrong in my code.

Your `GetAccessTocken` function does not appear to be following the instructions outlined in Microsoft's documentation:

https://learn.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth#get-an-access-token

Which authentication flow *exactly* are you trying to implement?  Your `POST` request is missing parameters in the `/token` request.

> # Below code sends email using manual commands.

And? What happens with it? Does it work or not?

> # Below code sends email using SASL.

You are adding 2 entries to the `SASLMechanisms` collection, where the 1st one is assigned a `TIdSASLXOAuth2` object that you are creating dynamically, but the 2nd one is assigned `SASLXOAuth2` which is *uninitialized*.

**Comment by varathasiva** [comment]
Hi,
Thanks for your support, now I can able to send email using the code below.
Please confirm the code is correct, I need one more help for upgrading latest Indy(10) on Delphi 10.2.3.
Last time I tried upgrading Delphi 10.2.3 Indy version to Indy(10) latest version, but it took lot of steps to do for manual upgradation.

Kindly provide your feedback & suggestion, I appreciate your response.

GetAccessToken:-
===========
var
  HttpClient: TNetHTTPClient;
  RequestBody: TStringStream;
  Response: IHTTPResponse;
  JsonObj: TJSONObject;
begin
  HttpClient := TNetHTTPClient.Create(nil);
  try
    RequestBody := TStringStream.Create('grant_type=client_credentials&client_id=' + ClientID +
      '&client_secret=' + ClientSecret +
      '&scope='+ Scope, TEncoding.Default);
    try
      Response := HttpClient.Post(TokenEndpoint, RequestBody);
      JsonObj := TJSONObject.ParseJSONValue(Response.ContentAsString) as TJSONObject;
      try
        Result := JsonObj.GetValue<string>('access_token');
      finally
        JsonObj.Free;
      end;
    finally
      RequestBody.Free;
    end;
  finally
    HttpClient.Free;
  end;

Sending Email: -
=========

const
  TokenEndpoint = 'https://login.microsoftonline.com/' + TenantID + '/oauth2/v2.0' + '/token';
  Scope = 'https://outlook.office365.com/.default';

var
  bUseSSL, bSMTP, bSMTPRelay, IsAuthenticated: boolean;
  sHost, sUserId, sPWD, sFromAddress, sToAddress, sPort, sErrMsg: string;
  iPortPos: integer;
  NameOfSMTPServer: string;
  SMTP: TIdSMTP;
  IdMsgSend: TIdMessage;
  IOHandlerSSL: TIdSSLIOHandlerSocketOpenSSL;
  UserPassProvider: TIdUserPassProvider;
  xoauthSASL: TIdSASLListEntry;
begin
  sHost         := edtEmailHost.Text;
  sUserId       := edtSMTPUserId.Text;
  sPWD          := edtSMTPPassword.Text;
  sFromAddress  := edtFromAddress.Text;
  sToAddress    := edtToAddress.Text;
  sUserId       := edtSMTPUserId.Text;
  sPWD          := edtSMTPPassword.Text;
  sToAddress    := 'sivasubramanian.varatharajan@azentio.com';//'fsql.support@azentio.com';

  SMTP := TIdSMTP.Create(nil);
  IdMsgSend := TIdMessage.Create(nil);
  IOHandlerSSL := TIdSSLIOHandlerSocketOpenSSL.Create(nil);
  try
    if sHost = '' then
      sHost  := SMTPServer + ':' + '587';
    bUseSSL     := rbSMTPUseSSLYes.Checked;
    SMTP.Username := FROMAddress;
    iPortPos := Pos(':', sHost);
    if iPortPos <> 0 then begin
      sPort        := Copy(sHost, iPortPos+1, Length(sHost));
      SMTP.Host    := Copy(sHost, 1, iPortPos-1);
    end
    else begin
      if IsAuthenticated
      then sPort    := '587'
      else sPort    := '25';
      SMTP.Host     := sHost;
    end;
    SMTP.Port       := StrToInt(sPort);

    IOHandlerSSL.Destination := SMTPServer + ':' + sPort;
    IOHandlerSSL.Host        := SMTPServer;
    IOHandlerSSL.Port        := StrToInt(sPort);
    IOHandlerSSL.DefaultPort := 0;

    IOHandlerSSL.SSLOptions.Method := sslvSSLv23; //sslvTLSv1_2;
    IOHandlerSSL.SSLOptions.Mode   := sslmUnassigned;
    IOHandlerSSL.SSLOptions.VerifyMode  := [];
    IOHandlerSSL.SSLOptions.VerifyDepth := 0;

    SMTP.IOHandler := IOHandlerSSL;
    SMTP.UseTLS := utUseExplicitTLS;

    sAccessToken := GetAccessTocken;//GetAccessToken(SMTPServer, sPort);

    UserPassProvider := TIdUserPassProvider.Create();

    UserPassProvider.Username := FROMAddress;
    UserPassProvider.Password := sAccessToken;

    SMTP.AuthType := satSASL;
    SMTP.SASLMechanisms.Clear;
    xOauthSASL := SMTP.SASLMechanisms.Add;

    xOauthSASL.SASL := TIdSASLXOAuth2.Create(nil);
    TIdSASLXOAuth2(xOauthSASL.SASL).UserPassProvider := UserPassProvider;
    TIdSASLXOAuth2(xOauthSASL.SASL).UserPassProvider.Username := FROMAddress;
    TIdSASLXOAuth2(xOauthSASL.SASL).UserPassProvider.Password := sAccessToken;

    IdMsgSend.Encoding := meMIME;
    IdMsgSend.CharSet := 'utf-8';
    IdMsgSend.Date := Now;
    IdMsgSend.ContentType := 'text/html; charset=UTF-8';
    IdMsgSend.From.Address := FROMAddress;  // Your email
    IdMsgSend.Recipients.EmailAddresses := sToAddress;
    IdMsgSend.Subject := 'This is test email';
    IdMsgSend.Body.Text := 'This is test email sent by Sample App using OAuth2 Token.';
    IdMsgSend.ContentType := 'multipart/related; type="text/html"';
    with TIdAttachmentFile.Create(IdMsgSend.MessageParts, 'C:\FactorSQL4\Output\Collections_v4.pdf') do
    begin
      ContentType    := 'Application/pdf';
      FileName    := ExtractFileName('C:\FactorSQL4\Output\Collections_v4.pdf');
    end;

    try
      SMTP.Connect;
      try
        SMTP.Send(IdMsgSend);
      except
        on E: Exception do
          ShowMessage('Failed to send email.  An error occurred whilst sending: "' + E.Message + '"');
      end;
      ShowMessage('Mail Sent! Successfully');
    finally
      SMTP.Disconnect;
    end;
  finally
    FreeAndNil(UserPassProvider);
    FreeAndNil(xOauthSASL);
//**    FreeAndNil(IDEncoder);
    SMTP.Free;
    IdMsgSend.Free;
  end;

Thanks & Regards
Siva

**Comment by varathasiva** [comment]
Hi,
Thanks for your support, now I can able to send email using the code below.
Please confirm the code is correct, I need one more help for upgrading latest Indy(10) on Delphi 10.2.3.
Last time I tried upgrading Delphi 10.2.3 Indy version to Indy(10) latest version, but it took lot of steps to do for manual upgradation.

Kindly provide your feedback & suggestion, I appreciate your 

GetAccessToken:-
===========
var
  HttpClient: TNetHTTPClient;
  RequestBody: TStringStream;
  Response: IHTTPResponse;
  JsonObj: TJSONObject;
begin
  HttpClient := TNetHTTPClient.Create(nil);
  try
    RequestBody := TStringStream.Create('grant_type=client_credentials&client_id=' + ClientID +
      '&client_secret=' + ClientSecret +
      '&scope='+ Scope, TEncoding.Default);
    try
      Response := HttpClient.Post(TokenEndpoint, RequestBody);
      JsonObj := TJSONObject.ParseJSONValue(Response.ContentAsString) as TJSONObject;
      try
        Result := JsonObj.GetValue<string>('access_token');
      finally
        JsonObj.Free;
      end;
    finally
      RequestBody.Free;
    end;
  finally
    HttpClient.Free;
  end;

Sending Email: -
=========

const
  TokenEndpoint = 'https://login.microsoftonline.com/' + TenantID + '/oauth2/v2.0' + '/token';
  Scope = 'https://outlook.office365.com/.default';

var
  bUseSSL, bSMTP, bSMTPRelay, IsAuthenticated: boolean;
  sHost, sUserId, sPWD, sFromAddress, sToAddress, sPort, sErrMsg: string;
  iPortPos: integer;
  NameOfSMTPServer: string;
  SMTP: TIdSMTP;
  IdMsgSend: TIdMessage;
  IOHandlerSSL: TIdSSLIOHandlerSocketOpenSSL;
  UserPassProvider: TIdUserPassProvider;
  xoauthSASL: TIdSASLListEntry;
begin
  sHost         := edtEmailHost.Text;
  sUserId       := edtSMTPUserId.Text;
  sPWD          := edtSMTPPassword.Text;
  sFromAddress  := edtFromAddress.Text;
  sToAddress    := edtToAddress.Text;
  sUserId       := edtSMTPUserId.Text;
  sPWD          := edtSMTPPassword.Text;
  sToAddress    := 'sivasubramanian.varatharajan@azentio.com';//'fsql.support@azentio.com';

  SMTP := TIdSMTP.Create(nil);
  IdMsgSend := TIdMessage.Create(nil);
  IOHandlerSSL := TIdSSLIOHandlerSocketOpenSSL.Create(nil);
  try
    if sHost = '' then
      sHost  := SMTPServer + ':' + '587';
    bUseSSL     := rbSMTPUseSSLYes.Checked;
    SMTP.Username := FROMAddress;
    iPortPos := Pos(':', sHost);
    if iPortPos <> 0 then begin
      sPort        := Copy(sHost, iPortPos+1, Length(sHost));
      SMTP.Host    := Copy(sHost, 1, iPortPos-1);
    end
    else begin
      if IsAuthenticated
      then sPort    := '587'
      else sPort    := '25';
      SMTP.Host     := sHost;
    end;
    SMTP.Port       := StrToInt(sPort);

    IOHandlerSSL.Destination := SMTPServer + ':' + sPort;
    IOHandlerSSL.Host        := SMTPServer;
    IOHandlerSSL.Port        := StrToInt(sPort);
    IOHandlerSSL.DefaultPort := 0;

    IOHandlerSSL.SSLOptions.Method := sslvSSLv23; //sslvTLSv1_2;
    IOHandlerSSL.SSLOptions.Mode   := sslmUnassigned;
    IOHandlerSSL.SSLOptions.VerifyMode  := [];
    IOHandlerSSL.SSLOptions.VerifyDepth := 0;

    SMTP.IOHandler := IOHandlerSSL;
    SMTP.UseTLS := utUseExplicitTLS;

    sAccessToken := GetAccessTocken;//GetAccessToken(SMTPServer, sPort);

    UserPassProvider := TIdUserPassProvider.Create();

    UserPassProvider.Username := FROMAddress;
    UserPassProvider.Password := sAccessToken;

    SMTP.AuthType := satSASL;
    SMTP.SASLMechanisms.Clear;
    xOauthSASL := SMTP.SASLMechanisms.Add;

    xOauthSASL.SASL := TIdSASLXOAuth2.Create(nil);
    TIdSASLXOAuth2(xOauthSASL.SASL).UserPassProvider := UserPassProvider;
    TIdSASLXOAuth2(xOauthSASL.SASL).UserPassProvider.Username := FROMAddress;
    TIdSASLXOAuth2(xOauthSASL.SASL).UserPassProvider.Password := sAccessToken;

    IdMsgSend.Encoding := meMIME;
    IdMsgSend.CharSet := 'utf-8';
    IdMsgSend.Date := Now;
    IdMsgSend.ContentType := 'text/html; charset=UTF-8';
    IdMsgSend.From.Address := FROMAddress;  // Your email
    IdMsgSend.Recipients.EmailAddresses := sToAddress;
    IdMsgSend.Subject := 'This is test email';
    IdMsgSend.Body.Text := 'This is test email sent by Sample App using OAuth2 Token.';
    IdMsgSend.ContentType := 'multipart/related; type="text/html"';
    with TIdAttachmentFile.Create(IdMsgSend.MessageParts, 'C:\FactorSQL4\Output\Collections_v4.pdf') do
    begin
      ContentType    := 'Application/pdf';
      FileName    := ExtractFileName('C:\FactorSQL4\Output\Collections_v4.pdf');
    end;

    try
      SMTP.Connect;
      try
        SMTP.Send(IdMsgSend);
      except
        on E: Exception do
          ShowMessage('Failed to send email.  An error occurred whilst sending: "' + E.Message + '"');
      end;
      ShowMessage('Mail Sent! Successfully');
    finally
      SMTP.Disconnect;
    end;
  finally
    FreeAndNil(UserPassProvider);
    FreeAndNil(xOauthSASL);
//**    FreeAndNil(IDEncoder);
    SMTP.Free;
    IdMsgSend.Free;
  end;

Thanks & Regards
Siva

**Comment by rlebeau** [comment]
> Hi, Thanks for your support, now I can able to send email using the code below. Please confirm the code is correct,

It looks fine (especially if it works), but it could use some cleanup.

> I need one more help for upgrading latest Indy(10) on Delphi 10.2.3.

That is not related to this issue and should be posted as its own separate ticket.
