### ISSUE TITLE
IdResourceStringsProtocols - incorrect spelling in rsHtmlViewerNeeded, rsRtfViewerNeeded 

### ISSUE THREAD

**Issue by hsvandrew** [IndySockets/Indy#557]
IdResourceStringsProtocols

  rsHtmlViewerNeeded = 'An HTML viewer is required to see this message';
  rsRtfViewerNeeded = 'An RTF viewer is required to see this message';

**Should be**  
  rsHtmlViewerNeeded = 'A HTML viewer is required to see this message';
  rsRtfViewerNeeded = 'A RTF viewer is required to see this message';

**Comment by asoio** [comment]
I think you're wrong. Most people pronounce HTML as "aitch tee em el" so "an HTML" is correct. The same applies to RTF ("arr tee eff").

**Comment by hsvandrew** [comment]
I can see your point about RTF, but disagree about the HTML one. https://www.scribbr.com/commonly-confused-words/a-vs-an/
Perhaps its due to the way English is spoken differently in different parts of the world but in Australian English, An HTML ... sounds very wrong.

**Comment by rlebeau** [comment]
On the flip side, for American English, "A HTML ..." and "A RTF ..." sound wrong to me.

In any case, these are just defaults.  For one thing, they are resource strings, so you can always localize them for different dialects of English if needed.  And second, the `TIdMessageBuilderHtml.HtmlViewerNeededMsg` and `TIdMessageBuilderRtf.RtfViewerNeededMsg` properties are public so you can change them to whatever you want.
